[config]

## Kitty
#[templates.kitty]
#input_path = '~/.config/matugen/templates/kitty-colors.conf'
#output_path = '~/.config/kitty/matugen/colors.conf'
#
## Hyprland
#[templates.hyprland]
#input_path = '~/.config/matugen/templates/hyprland-colors.conf'
#output_path = '~/.config/hypr/matugen/colors.conf'

# Gtk3
[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'

# Gtk4
[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

## Qt5
#[templates.qt5]
#input_path = '~/.config/matugen/templates/qtct-colors.conf'
#output_path = '~/.config/qt5ct/colors/matugen-qt5ct.conf'
#
## Qt6
#[templates.qt6]
#input_path = '~/.config/matugen/templates/qtct-colors.conf'
#output_path = '~/.config/qt6ct/colors/matugen-qt6ct.conf'
#
## Kvantum
#[templates.kvantum]
#input_path = '~/.config/matugen/templates/kvantum.kvconfig'
#output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'
#
## Spicetify
#[templates.spicetify]
#input_path = '~/.config/matugen/templates/spotify.ini'
#output_path = '~/.config/spicetify/Themes/Comfy/color.ini'
#
## Slack
#[templates.slack]
#input_path = "~/.config/matugen/templates/slack.tera"
#output_path = "~/.cache/matugen/slack-theme.txt"
#
## walker
#[templates.walker]
#input_path = "~/.config/matugen/templates/walker.css"
#output_path = "~/.config/walker/themes/matugen/colors.css"
